<a href="https://colab.research.google.com/github/adityadhumal06/Natural_Language_Processing/blob/main/Feature_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = {'text':['People watch campusx',
                'campusx watch campusx',
                'people write comment',
                'campusx write comment'],
        'output': [1,1,0,0] }

In [4]:
df

{'text': ['People watch campusx',
  'campusx watch campusx',
  'people write comment',
  'campusx write comment'],
 'output': [1, 1, 0, 0]}

In [5]:
df = pd.DataFrame(df)

In [6]:
df

text  output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [7]:
x = df[['text']]
y = df[['output']]

In [8]:
# Bag of words
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
bow = vector.fit_transform(df['text'])
bow

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [9]:
# vocab
print(vector.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [10]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [11]:
df['text'][0]

'People watch campusx'

In [12]:
bow[1].toarray()

array([[2, 0, 0, 1, 0]])

In [13]:
df['text'][1]

'campusx watch campusx'

In [14]:
vector.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

In [15]:
# bi-gram

In [16]:
df

text  output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer(ngram_range=(2,2))


In [18]:
bow = vector.fit_transform(df['text']).toarray()
bow

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [19]:
# vocb
vector.vocabulary_

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comment': 5,
 'campusx write': 1}

In [22]:
bow[0]

array([0, 0, 1, 0, 1, 0])

In [23]:
df

text  output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [39]:
bow[2]

array([0, 0, 0, 1])

In [ ]:
bow.toarray()

In [25]:
# tri- grams

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer(ngram_range=(3,3))


In [27]:
bow = vector.fit_transform(df['text']).toarray()
bow

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [28]:
# vocb
vector.vocabulary_

{'people watch campusx': 2,
 'campusx watch campusx': 0,
 'people write comment': 3,
 'campusx write comment': 1}

In [29]:
bow[2]

array([0, 0, 0, 1])

**TF-IDF VECTORIZER**

In [30]:
df

text  output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
tf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [40]:
  print(tf.idf_) # constant value

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


In [38]:
print(tf.idf_)
print(tf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
