<a href="https://colab.research.google.com/github/adityadhumal06/Natural_Language_Processing/blob/main/Feature_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = {'text':['People watch campusx',
                'campusx watch campusx',
                'people write comment',
                'campusx write comment'],
        'output': [1,1,0,0] }

In [ ]:
df

{'text': ['People watch campusx',
  'campusx watch campusx',
  'people write comment',
  'campusx write comment'],
 'output': [1, 1, 0, 0]}

In [ ]:
df = pd.DataFrame(df)

In [ ]:
df

text  output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
x = df[['text']]
y = df[['output']]

In [ ]:
# Bag of words
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
bow = vector.fit_transform(df['text'])
bow

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [ ]:
# vocab
print(vector.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [ ]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [ ]:
df['text'][0]

'People watch campusx'

In [ ]:
bow[1].toarray()

array([[2, 0, 0, 1, 0]])

In [ ]:
df['text'][1]

'campusx watch campusx'

In [ ]:
vector.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

In [ ]:
# bi-gram

In [ ]:
df

text  output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer(ngram_range=(2,2))


In [ ]:
bow = vector.fit_transform(df['text']).toarray()
bow

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [ ]:
# vocb
vector.vocabulary_

{'people watch': 2,
 'watch campusx': 4,
 'campusx watch': 0,
 'people write': 3,
 'write comment': 5,
 'campusx write': 1}

In [ ]:
bow[0].toarray()

array([[0, 0, 1, 0, 1, 0]])

In [ ]:
df

text  output
0   People watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [ ]:
bow[2].toarray()

array([[0, 0, 0, 1, 0, 1]])

In [ ]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [ ]:
# tri- grams

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer(ngram_range=(3,3))


In [ ]:
bow = vector.fit_transform(df['text']).toarray()
bow

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [ ]:
# vocb
vector.vocabulary_

{'people watch campusx': 2,
 'campusx watch campusx': 0,
 'people write comment': 3,
 'campusx write comment': 1}

In [ ]:
bow[2]

array([0, 0, 0, 1])